/*
 * generated by Xtext
 */
package plsql.editor.xtext.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class PlSqlUiModule extends plsql.editor.xtext.ui.AbstractPlSqlUiModule {
	public PlSqlUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
