/*
 * generated by Xtext
 */
package plsql.editor.xtext;

/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
public class PlSqlRuntimeModule extends plsql.editor.xtext.AbstractPlSqlRuntimeModule {

}
