/*
 * generated by Xtext
 */
package plsql.editor.xtext.ui.contentassist;


/**
 * see
 * http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on
 * how to customize content assistant
 */
public class PlSqlProposalProvider extends AbstractPlSqlProposalProvider {

	@Override
	protected boolean doCreateIntProposals() {
		return false;
	}

	@Override
	protected boolean doCreateStringProposals() {
		return false;
	}

	@Override
	protected boolean doCreateIdProposals() {
		return false;
	}
}
