
/*
 * generated by Xtext
 */
 
package plsql.editor.xtext.ui;

import org.eclipse.xtext.ui.guice.AbstractGuiceAwareExecutableExtensionFactory;
import org.osgi.framework.Bundle;

import com.google.inject.Injector;

/**
 *@generated
 */
public class PlSqlExecutableExtensionFactory extends AbstractGuiceAwareExecutableExtensionFactory {

	@Override
	protected Bundle getBundle() {
		return plsql.editor.xtext.ui.internal.PlSqlActivator.getInstance().getBundle();
	}
	
	@Override
	protected Injector getInjector() {
		return plsql.editor.xtext.ui.internal.PlSqlActivator.getInstance().getInjector("plsql.editor.xtext.PlSql");
	}
	
}
